name: CI
on:
  push:
    branches: [ llvm ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install lit
        run: pip install lit
      - name: Build
        run: cargo build --verbose
      - name: Unit tests
        run: cargo test --verbose
      - name: Integration tests
        run: lit -v compile-tests