name: CI
on:
  push:
    branches: [ llvm ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v3
        with:
          path: |
            ./llvm
          key: llvm-3.5
      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Install lit
        run: pip install lit
      - name: Build
        run: cargo build --verbose
      - name: Unit tests
        run: cargo test --verbose
      - name: Integration tests
        run: lit -v compile-tests