name: CI
on:
  push:
    branches: [ llvm ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v21
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - uses: cachix/cachix-action@v12
        with:
          name: veridise-private
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - name: Install LLVM
        run: sudo apt-get install -y llvm-13 llvm-13-tools llvm-13-dev llvm-13-runtime
      - name: Link llvm-config-13 to llvm-config
        run: sudo ln -s /usr/bin/llvm-config-13 /usr/bin/llvm-config
      - name: Install lit
        run: pip install lit
      - name: Build
        run: nix-build --print-build-logs
      - name: Manually build for now
        run: cargo build release
      - name: Integration tests
        run: lit -v circom/tests