name: CI
on:
  push:
    branches: [ llvm ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - uses: cachix/install-nix-action@v21
        with:
          install_url: https://releases.nixos.org/nix/nix-2.13.3/install
      - uses: cachix/cachix-action@v12
        with:
          name: veridise-public
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix-build --print-build-logs