on:
  pull_request:
    types: ['closed']
    branches: [ llvm ]


name: Transition Issue to Done

jobs:
  transition-issue:
    if: 'github.event.pull_request.merged == true'
    name: Transition Issue to In Review
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        submodules: recursive
        persist-credentials: false

    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Find Issue Key
      id: find
      uses: atlassian/gajira-find-issue-key@v3
      continue-on-error: true
      with:
        string: ${{ github.head_ref }}

    - name: Transition issue
      uses: atlassian/gajira-transition@v3
      continue-on-error: true
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: Merged
